const PRODUCTS = [
  { id: 'xm5', name: 'Sony WH-1000XM5 Wireless Headphones', price: 29990, mrp: 34990, emoji: '🎧', hue: 210, rating: 4.7, reviews: 12843, tag: 'Best Seller', blurb: 'Silence, but expensive. Eight mics so the world can\'t reach you, 30-hour battery so it stays that way.' },
  { id: 'k8pro', name: 'Keychron K8 Pro QMK Mechanical Keyboard', price: 9499, mrp: 11999, emoji: '⌨️', hue: 160, rating: 4.6, reviews: 3421, tag: 'Deal of the Day', blurb: 'Hot-swappable, gasket-mounted, thocc included. Your Excel models will sound expensive.' },
  { id: 'uw34', name: 'LG 34" UltraWide Curved Monitor WQHD', price: 38500, mrp: 52000, emoji: '🖥️', hue: 200, rating: 4.5, reviews: 876, tag: 'Limited Deal', blurb: 'For Prophet models that deserve width. See column XFD without scrolling.' },
  { id: 'sqoff', name: 'Square Off Grand Kingdom Chess Set', price: 39999, mrp: 45999, emoji: '♟️', hue: 30, rating: 4.4, reviews: 512, tag: 'Wow', blurb: 'The pieces move themselves. So will your weekends. Play anyone, anywhere, on actual wood.' },
  { id: 'pegasus', name: 'Nike Air Zoom Pegasus Running Shoes', price: 10795, mrp: 12795, emoji: '👟', hue: 20, rating: 4.5, reviews: 9230, tag: 'Best Seller', blurb: 'For the 5 AM airport sprint. Cushioned enough to forgive the terminal length.' },
  { id: 'biz', name: 'Upgrade: BOM to AUH, Business Class', price: 48000, mrp: 72500, emoji: '✈️', hue: 250, rating: 4.9, reviews: 207, tag: 'Expiring Soon', blurb: 'Boards in under an hour. Coincidence? Lie-flat seat, lounge access, and smugness included.' },
  { id: 'bambino', name: 'Breville Bambino Plus Espresso Machine', price: 42000, mrp: 47900, emoji: '☕', hue: 25, rating: 4.6, reviews: 2210, tag: 'Cult Favorite', blurb: 'Crema over sleep. Three-second heat-up, microfoam that makes Mondays negotiable.' },
  { id: 'garmin', name: 'Garmin Forerunner 265 GPS Watch', price: 34990, mrp: 41990, emoji: '⌚', hue: 140, rating: 4.7, reviews: 1544, tag: 'New', blurb: 'Counts your steps to the boarding gate. AMOLED screen, two-week battery, zero excuses.' },
  { id: 'remarkable', name: 'reMarkable 2 Paper Tablet', price: 43999, mrp: 46999, emoji: '📝', hue: 0, rating: 4.3, reviews: 689, tag: 'Minimal', blurb: 'Paper that syncs. Witchcraft. Zero apps, zero notifications, all thoughts.' },
  { id: 'kindle', name: 'Kindle Paperwhite (16 GB)', price: 16999, mrp: 18999, emoji: '📚', hue: 190, rating: 4.6, reviews: 45123, tag: 'Best Seller', blurb: 'Airport fiction, unlimited. Warm light for the red-eye, weeks of battery for the layover.' },
  { id: 'prophet', name: 'Prophet Personal Edition (Annual License)', price: 100000, mrp: 250000, emoji: '💾', hue: 220, rating: 3.9, reviews: 12, tag: 'Niche', blurb: 'Actuarial modelling, but for fun at home. The license server judges silently. 60% off, actuary price.' },
  { id: 'sp1', name: 'Framed Motivational Poster: "You Passed SP1"', price: 499, mrp: 1499, emoji: '🖼️', hue: 45, rating: 4.8, reviews: 9999, tag: 'Manifesting', blurb: 'Manifesting, framed. Hang it above the study desk and let the law of attraction do the revision.' },
  { id: 'dxbchoc', name: 'FIX Dubai Chocolate - The Kunafa One', price: 2400, mrp: 3200, emoji: '🍫', hue: 35, rating: 4.9, reviews: 31415, tag: 'Viral', blurb: 'Obviously. Pistachio, kunafa crunch, and the reason your flight to Dubai was inevitable.' },
  { id: 'desk', name: 'Electric Standing Desk 140cm', price: 22999, mrp: 29999, emoji: '🪑', hue: 100, rating: 4.4, reviews: 1876, tag: 'WFH Essential', blurb: 'Your lumbar sends thanks in advance. Four memory presets, one for each posture lie.' }
];
